### ISSUE TITLE
prefix naming convention ?

### ISSUE THREAD

**Issue by tsugliani** [mycloudrevolution/VMware-NSXvCD-Module#14]
Hi @mycloudrevolution,

I just took a very quick look at the documentation, and there is just one thing bothering me is the very generic names for the following functions:

- `Invoke-APICall`
- `New-APIConnection`

I suspect prefixing them with `NsxVcd` would probably be more consistent ?
It's likely that some other people might be using those "generic" names and would avoid any conflict.

Thoughts ?

**Comment by mycloudrevolution** [comment]
I agree.

I will schedule that for the next minor release.

**Comment by mycloudrevolution** [comment]
Might you please have a look at this branch:
https://github.com/mycloudrevolution/VMware-NSXvCD-Module/tree/v1.1
